### ISSUE TITLE
Implement delete_by_query as scan and bulk delete

### ISSUE THREAD

**Issue by grantr** [github/elastomer-client#104]
The `delete_by_query` API is going away in ES 2.0 because of multiple issues (See https://www.elastic.co/blog/core-delete-by-query-is-a-plugin). The alternative is a combination scan and bulk delete.

We should make the change in elastomer-client now to prep for the ES 2.0 upgrade.

/cc @TwP

**Comment by chrismwendt** [comment]
Should the command be renamed as well? Doing so would avoid some confusion like "I thought this API was removed in 2.0?", but it would be more work to find all references to `delete_by_query` and rename them.

**Comment by grantr** [comment]
@chrismwendt Good question. Can we gather some data to find out how often this command is used? I suspect it's mostly used in test/dev code. Here's a search for it: https://github.com/search?p=1&q=%40github+delete_by_query&type=Code&utf8=%E2%9C%93

I can't think of a better name than `delete_by_query`, can you?

**Comment by chrismwendt** [comment]
It's hard to say how much it's used, and I can't think of a better name either. Perhaps it's appropriate to leave the name the same because the implementation, not the functionality, will change.

**Comment by TwP** [comment]
My vote is to leave the `delete_by_query` name in place. The scan / bulk delete approach will word on versions of ES prior to 2.0, and this approach is *safer* than the current `delete_by_query` implementation in ES itself. So hiding this endpoint from the user is a good, opinionated change to make. We should absolutely update the method documentation to let people know what is going on under the hood.

**Comment by chrismwendt** [comment]
Implemented in #108.
