### ISSUE TITLE
Style guide cleanup

### ISSUE THREAD

**Issue by TwP** [github/elastomer-client#110]
We are following GitHub's [ruby style guide](https://github.com/styleguide/ruby), but there are many places in the codebase where the style guide has been ignored:

* whitespace between parentheses and values
* single character variable names should be eschewed
* quotes `"good"` should be used for strings instead of apostrophes `'bad'`
* hashrockets `=>` should be used instead of the JSON style `:` in hashes
* trailing whitespace

Please add others to this list so I can do a sweep and fix my wayward coding style.

/cc @grantr @chrismwendt

**Comment by chrismwendt** [comment]
I added the quotes, hashrockets, and trailing whitespace points since I have witnessed or committed such atrocities myself.

Perhaps we could establish a pre-commit hook to run a style check.

**Comment by TwP** [comment]
[Rubocop](https://github.com/bbatsov/rubocop) seems to be the Ruby style checker de jour. We could throw that into a pre-push hook on the project much like puppet does for validating puppet files. Rubcop would run locally then before pushing changes up to the origin repository.

Good idea, @chrismwendt :clap: :+1: :sparkles:

**Comment by chrismwendt** [comment]
#111 cleaned up all but the single-character variable names. @TwP: it's your call if you would like to close this issue.

**Comment by TwP** [comment]
Single variable names are fine. :+1: on closing this out, and :bow: @chrismwendt for getting rubocop up an running on this repo.
