### ISSUE TITLE
Exclude source retrieval in delete_by_query

### ISSUE THREAD

**Issue by TwP** [github/elastomer-client#117]
The `delete_by_query` call should exclude the document source from being retrieved when performing the scan operation. We only need the `index`, `type`, and `id` of the documents in order to delete them. Excluding source retrieval will reduce load on the search cluster, and it will reduce the size of our HTTP packets.

```ruby
@query = query.dup
@query.delete :_source if @query.key? :_source
@query.delete "_source" if @query.key? "_source"
@query[:_source] = false 
```

Example implementation to put into the `DeleteByQuery` initializer.

/cc @chrismwendt @grantr

**Comment by grantr** [comment]
Definitely :+1: although we should check to make sure all of our deployed versions support this.

**Comment by TwP** [comment]
Agreed - I was attempting to dig through the Elasticsearch docs to find when / where the `_source` field was introduced. It was formerly the `fields` keyword in the query document. I'll do a little more digging.

**Comment by chrismwendt** [comment]
According to https://www.elastic.co/guide/en/elasticsearch/reference/1.3/search-request-source-filtering.html#search-request-source-filtering, the `_source` field was added in ES 1.0.0.Beta1.

**Comment by chrismwendt** [comment]
Done in #119.
