### ISSUE TITLE
Consider utilizing Elasticsearch Transport for communication not standard HTTP API

### ISSUE THREAD

**Issue by kkirsche** [github/elastomer-client#124]
For better performance, consider using the [Elasticsearch Transport](https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-transport) which handles connecting to multiple nodes in the cluster, rotating across connections, logging and tracing requests and responses, maintaining failed connections, discovering nodes in the cluster, and provides an abstraction for data serialization and transport.

This should also be able to allow the use of Excon, Patron and other adapters in a similar manner to what you have which are supported with Elasticsearch's official client

**Comment by elireisman** [comment]
I'm closing this, latest recommends for newer ES versions are not to use this, perf change is negligible too.
